window.LENS_PROFILES = {
  clear: {
    nav: "Clear",
    symbol: "01",
    color: "#196a78",
    soft: "#dcebed",
    label: "Clear lens",
    title: "The system-seeing creator",
    body:
      "Andrij is a Ukrainian-born, Czech-rooted project builder based in Prague. He works where strategy meets reality: diagnosing blockers across people, offers, workflows, communication, physical spaces, and business models, then turning the diagnosis into a useful next step.",
    notes: [
      "Systems advisor in development",
      "Strategy translated into action",
      "Multilingual and intercultural",
      "AI-native, human-centered",
    ],
    cards: [
      {
        eyebrow: "Core value",
        title: "Diagnose",
        body: "He sees where trust, attention, money, communication, or responsibility stops moving — and names the blockage without making the system more complicated.",
      },
      {
        eyebrow: "Working mode",
        title: "Build",
        body: "Ideas become prototypes, offers, content systems, websites, automation, launch plans, and practical experiments that can be tested in the real world.",
      },
      {
        eyebrow: "Human edge",
        title: "Connect",
        body: "Six languages, international projects, facilitation, photography, community work, and hands-on operations help him translate between very different people.",
      },
      {
        eyebrow: "Direction",
        title: "Make it useful",
        body: "The aim is not advice for its own sake. It is a clearer project, a stronger person, a healthier system, and enough momentum for the next honest step.",
      },
    ],
    facets: [
      { name: "What I notice", value: "The invisible blockage", detail: "Where people, offers, workflows, space, communication, and business logic stop supporting each other." },
      { name: "What I bring", value: "Structure with movement", detail: "A diagnosis becomes a map; the map becomes a prototype; the prototype creates evidence." },
      { name: "Proof in the path", value: "Many practical worlds", detail: "Construction, photography, HR, events, ecology, education, media, AI, and project coordination." },
      { name: "Best fit", value: "Messy, meaningful projects", detail: "Founders, studios, communities, and initiatives that have real value but need clearer systems." },
      { name: "Working promise", value: "No theatre of expertise", detail: "Observe carefully, explain simply, build visibly, and stay close to what actually changes the situation." },
      { name: "Next chapter", value: "Systems advisor", detail: "A professional identity that joins marketing, automation, project building, and human understanding." },
    ],
    meters: [76, 88, 82],
    closing: "See the whole. Find the blockage. Build the next useful thing.",
  },
  personal: {
    nav: "Personal",
    symbol: "02",
    color: "#8a5c43",
    soft: "#efe2d8",
    label: "Personal lens",
    title: "A bridge between survival, sensitivity, and building",
    body:
      "My story is not a straight career line. It moves through Ukraine and Czech life, village roots and early independence, family loss, sport, photography, physical work, volunteering, anxiety, sobriety, community, and a long search for a cleaner way to live. I am turning that path into useful work without sanding away its human edges.",
    notes: [
      "Village roots near Drohobych",
      "Ukraine, Czechia, and Europe",
      "Sensitivity became an instrument",
      "Success must still feel human",
    ],
    cards: [
      {
        eyebrow: "Roots",
        title: "Land before LinkedIn",
        body: "A Ukrainian family story, village childhood, craft, physical work, food, home, and the understanding that real things require hands as well as ideas.",
      },
      {
        eyebrow: "Inner pattern",
        title: "Feel deeply, inspect closely",
        body: "Sensitivity to tension and injustice can be heavy, but it also reveals what a room, team, or system is trying not to say.",
      },
      {
        eyebrow: "Transformation",
        title: "From coping to choosing",
        body: "Anxiety, difficult periods, sobriety, psychology, spiritual practice, and community life reshaped the question from “How do I survive?” to “What do I build?”",
      },
      {
        eyebrow: "Compass",
        title: "A life with a center",
        body: "Family, nature, useful work, meaningful travel, craft, and a home worth returning to are not a retirement plan. They are the design brief.",
      },
    ],
    facets: [
      { name: "What I notice", value: "What is not being said", detail: "The emotional weather beneath a plan, the hesitation behind a task, and the human cost of a broken system." },
      { name: "What I bring", value: "Earned empathy", detail: "Not abstract positivity — patience shaped by rebuilding, adapting, and beginning again in different places." },
      { name: "Proof in the path", value: "Life across borders", detail: "Ukraine, Czechia, Poland, Sweden, Hungary, and projects across Europe taught me to enter new contexts carefully." },
      { name: "Best fit", value: "People in transition", detail: "Founders, creators, teams, and individuals between an old identity and a more honest next version." },
      { name: "Working promise", value: "I will not reduce you", detail: "The business problem may be real, but so are the identity, energy, fear, and relationships around it." },
      { name: "Next chapter", value: "Strength without hardness", detail: "Build a mature professional life while keeping curiosity, tenderness, and responsibility alive." },
    ],
    meters: [94, 71, 89],
    closing: "The path was not tidy. The meaning can still be clear.",
  },
  funny: {
    nav: "Funny",
    symbol: "03",
    color: "#a66b16",
    soft: "#f5e8c8",
    label: "Funny lens",
    title: "An entrepreneur for the soul, with seventeen tabs open",
    body:
      "I can discuss SEO funnels, family values, AI automation, permaculture, why your studio needs more plants, and why nobody understands the offer — possibly in the same coffee. The method is multidisciplinary. The browser situation is irresponsible. The intention is sincere.",
    notes: [
      "Professional overthinker, now billable",
      "Can prototype before the meeting ends",
      "Plants are sometimes strategy",
      "Spreadsheets, but make them alive",
    ],
    cards: [
      {
        eyebrow: "Special ability",
        title: "Translate chaos",
        body: "Give me twelve voice notes, three contradictory documents, an unfinished website, and one vague dream. I will return with a map and several new tabs.",
      },
      {
        eyebrow: "Career path",
        title: "Yes, also that",
        body: "Photographer? Yes. Construction? Yes. HR, events, ecology, education, media, AI, marketing? Unfortunately for the short biography, also yes.",
      },
      {
        eyebrow: "Management style",
        title: "Serious about useful",
        body: "Not every process needs a dashboard. Some need one honest conversation. Some need a checklist. A few need a plant and better lighting.",
      },
      {
        eyebrow: "Long-term plan",
        title: "Build everything, calmly",
        body: "Agency, platform, media ecosystem, community, house in nature, workshop, family — in a perfectly sensible order that has not yet revealed itself.",
      },
    ],
    facets: [
      { name: "What I notice", value: "The weirdly specific problem", detail: "The button is fine. The offer is confused. The room is cold. Nobody owns follow-up. Also, the plant is dying." },
      { name: "What I bring", value: "Useful curiosity", detail: "Enough questions to find the real problem, then enough pragmatism to stop asking and make something." },
      { name: "Proof in the path", value: "A suspicious number of skills", detail: "The CV looks less like a ladder and more like someone emptied a toolbox onto the floor." },
      { name: "Best fit", value: "Founders with too much brain", detail: "You have a strong idea, nineteen possible directions, and a homepage that explains none of them." },
      { name: "Working promise", value: "We may laugh, but we will ship", detail: "Humor lowers the pressure. Clear ownership and a visible next step keep it from becoming avoidance." },
      { name: "Next chapter", value: "Fewer tabs, better systems", detail: "Automation should create room for life, not give us a more efficient way to be overwhelmed." },
    ],
    meters: [91, 83, 97],
    closing: "Make it work. Make it human. Please name the final file correctly.",
  },
  dramatic: {
    nav: "Drama",
    symbol: "04",
    color: "#b44935",
    soft: "#f2ddd7",
    label: "Dramatic lens",
    title: "From chaos into architecture",
    body:
      "There were years of pressure, displacement, conflict with systems, inner storms, and the feeling that the world had too many broken structures and too little tenderness. The answer became not escape, but architecture: build media, platforms, communities, businesses, and a home — and turn the wound into a working instrument.",
    notes: [
      "The border became a bridge",
      "The wound became a sensor",
      "The many paths became a method",
      "The future became something to build",
    ],
    cards: [
      {
        eyebrow: "Act I",
        title: "Between worlds",
        body: "Ukraine and Czechia. Village and capital. Physical work and digital systems. The story begins in the tension between places that were never truly separate.",
      },
      {
        eyebrow: "Act II",
        title: "The breaking point",
        body: "Loss, anxiety, displacement, and resistance to harmful systems made ordinary career language feel too small for the real work of becoming.",
      },
      {
        eyebrow: "Act III",
        title: "The instrument",
        body: "What once felt like too much sensitivity became a way to detect weak structures, defend dignity, and understand why people or projects freeze.",
      },
      {
        eyebrow: "Act IV",
        title: "Build the answer",
        body: "The answer is not a perfect personal brand. It is an ecosystem sturdy enough to hold work, family, community, nature, and contribution together.",
      },
    ],
    facets: [
      { name: "What I notice", value: "Where the system fractures", detail: "A quiet point where trust disappears, responsibility dissolves, and the official story no longer matches reality." },
      { name: "What I bring", value: "Pressure-tested vision", detail: "A refusal to accept that broken structures are permanent simply because people became used to them." },
      { name: "Proof in the path", value: "Rebuilding as practice", detail: "Across countries, communities, jobs, and personal transformation, starting again became a repeatable skill." },
      { name: "Best fit", value: "The consequential moment", detail: "A project has meaning, but it is stuck; a person has ability, but no structure; a system has resources, but no soul." },
      { name: "Working promise", value: "Name the real conflict", detail: "Drama becomes useful when it stops being atmosphere and reveals the decision everyone is avoiding." },
      { name: "Next chapter", value: "Architecture for dignity", detail: "Build systems where professional success and human depth reinforce rather than cancel each other." },
    ],
    meters: [88, 96, 84],
    closing: "Do not decorate the chaos. Give it structure.",
  },
  motivation: {
    nav: "Motivation",
    symbol: "05",
    color: "#617542",
    soft: "#e3ead7",
    label: "Motivation lens",
    title: "Learn what is needed. Build what is missing.",
    body:
      "Andrij's direction is built on practical faith in the process: study the problem, enter the real context, make the first version, collect evidence, and improve. The path across industries is not wasted motion. It is proof that a new capability can be learned and put to work.",
    notes: [
      "Movement creates clarity",
      "Learning is part of delivery",
      "Small proof beats big theatre",
      "Success should support others",
    ],
    cards: [
      {
        eyebrow: "Step one",
        title: "Face the real situation",
        body: "No borrowed confidence and no fantasy plan. Start with the actual resources, actual skills, actual obstacles, and the truth about what has not worked yet.",
      },
      {
        eyebrow: "Step two",
        title: "Create visible proof",
        body: "A prototype, project page, client improvement, useful piece of content, workshop, or working automation changes the conversation more than another promise.",
      },
      {
        eyebrow: "Step three",
        title: "Build the capability",
        body: "AI-assisted development, marketing, facilitation, public communication, and systems thinking grew through active projects, not permission from a perfect title.",
      },
      {
        eyebrow: "Step four",
        title: "Let success carry weight",
        body: "The target is mastery that supports family, nature, meaningful travel, community, and projects that improve real human life.",
      },
    ],
    facets: [
      { name: "What I notice", value: "The next movable piece", detail: "Even in a large problem, one decision, conversation, prototype, or responsibility can restore momentum." },
      { name: "What I bring", value: "Builder energy", detail: "A bias toward creating something we can inspect together instead of debating an idea forever." },
      { name: "Proof in the path", value: "Repeated reinvention", detail: "New countries, fields, tools, and roles became laboratories for learning how to learn under real conditions." },
      { name: "Best fit", value: "Ambition without a route", detail: "The direction matters, the energy exists, but the road from idea to weekly action is still missing." },
      { name: "Working promise", value: "Turn hope into sequence", detail: "Make the goal concrete, define the first evidence, and create a rhythm that survives imperfect weeks." },
      { name: "Next chapter", value: "Mastery with purpose", detail: "Become known for solving meaningful problems and leave stronger systems behind." },
    ],
    meters: [86, 93, 79],
    closing: "You do not need the whole road. You need an honest next step.",
  },
  romantic: {
    nav: "Romantic",
    symbol: "06",
    color: "#7a566d",
    soft: "#eadfe7",
    label: "Romantic lens",
    title: "A house in nature, a desk full of projects, and people worth helping",
    body:
      "At the heart of everything is a quiet wish: to live close to nature with family, create useful work, travel when a meaningful project needs help, and return to a home that feels like peace. Business is not only for money. It is a road toward dignity, love, land, craft, and ambition with a human face.",
    notes: [
      "Home is the center of gravity",
      "Work can be an act of care",
      "Technology should return us to life",
      "Ambition needs somewhere to come home",
    ],
    cards: [
      {
        eyebrow: "Home",
        title: "The center of gravity",
        body: "A house near nature, family, children, trees, food, silence, tools, and a table where projects can grow without consuming the whole life around them.",
      },
      {
        eyebrow: "Work",
        title: "Useful beauty",
        body: "A clear system can feel beautiful because it gives people room to breathe. A good brand can be honest. A business can grow without becoming empty.",
      },
      {
        eyebrow: "Journey",
        title: "Travel with a reason",
        body: "Go where a project, community, or person can use the help; learn from another place; carry something useful back home.",
      },
      {
        eyebrow: "Legacy",
        title: "Things that keep living",
        body: "A workshop, a platform, a community, a healthier business, a planted landscape, a family story — structures that continue to hold life after the launch.",
      },
    ],
    facets: [
      { name: "What I notice", value: "The life inside the system", detail: "Whether a project gives people energy, belonging, beauty, dignity, and a reason to care beyond the metric." },
      { name: "What I bring", value: "A wider definition of value", detail: "Money matters. So do time, place, relationships, health, craft, nature, and the memory a project leaves." },
      { name: "Proof in the path", value: "Communities and land", detail: "Village roots, ecology, permaculture, international volunteering, community spaces, and practical making." },
      { name: "Best fit", value: "Work that wants a soul", detail: "A studio, founder, wellness space, educational project, community, or ethical business that refuses to be generic." },
      { name: "Working promise", value: "Protect the reason", detail: "Growth is useful only if the thing that made the project worth building remains visible inside it." },
      { name: "Next chapter", value: "A life that coheres", detail: "Professional mastery, family, nature, travel, creativity, and contribution — designed as one ecosystem." },
    ],
    meters: [98, 77, 91],
    closing: "Build a life where ambition still knows the way home.",
  },
};
